#:schema node_modules/wrangler/config-schema.json
name = "image-host"
main = "src/index.ts"
compatibility_date = "2024-09-19"
compatibility_flags = ["nodejs_compat"]

[placement]
mode = "smart"

[vars]
CDN_URL = "https://cdn.image-host.scheenen.dev"

# Bind a D1 database. D1 is Cloudflare’s native serverless SQL database.
# Docs: https://developers.cloudflare.com/workers/wrangler/configuration/#d1-databases
[[d1_databases]]
binding = "DB"
database_name = "image-host"
database_id = "155b308e-ab88-4703-9cff-52f897f7eb3a"

# Bind an R2 Bucket. Use R2 to store arbitrarily large blobs of data, such as files.
# Docs: https://developers.cloudflare.com/workers/wrangler/configuration/#r2-buckets
[[r2_buckets]]
binding = "IMG_STORAGE"
bucket_name = "image-host"
